name: kubedmp
summary: Display kubectl cluster-info dump output in a human readable way 
description: |
      kubectl cluster-info dump writes data in yaml format. This tool displays
      them in a format similar to output of kubectl get/describe resources.
adopt-info: kubedmp
grade: stable
base: core20

confinement: devmode

apps:
  kubedmp:
    command: bin/kubedmp
    plugs:
      - home
parts:
  kubedmp:
    plugin: go
    source: .
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version “$(git describe —-tags)”
    override-build: |
      make build
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/
      mv bin/kubedmp $SNAPCRAFT_PART_INSTALL/bin/