name: release

on:
  push:
    tags:
      - '*'

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build
        run: make build
      - name: version
        run: echo "::set-output name=version::$(./bin/kubedmp -v | grep Version | cut -f2 -d' ')"
        id: version
      - name: build artifacts
        run: make bin
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/kubedmp_linux_amd64.tar.gz
          asset_name: kubedmp_linux_amd64.tar.gz
          asset_content_type: application/gzip
      - name: upload darwin arm64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/kubedmp_darwin_arm64.tar.gz
          asset_name: kubedmp_darwin_arm64.tar.gz
          asset_content_type: application/gzip
      - name: upload darwin amd64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/kubedmp_darwin_amd64.tar.gz
          asset_name: kubedmp_darwin_amd64.tar.gz
          asset_content_type: application/gzip
      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/kubedmp_windows_amd64.zip
          asset_name: kubedmp_windows_amd64.zip
          asset_content_type: application/zip