name: release

on:
  push:
    tags:
      - '*'

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      # - name: Run tests
      #   run: go test -v ./...
      - name: install snapcraft
        run: |
          sudo apt-get update -q
          sudo apt-get install -qy snapd
          sudo snap install snapcraft --classic
      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --clean --release-notes CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
